name: 'fraud_detection_analytics'
version: '1.0.0'
config-version: 2

profile: 'fraud_detection'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fraud_detection_analytics:
    gold:
      +materialized: table

seeds:
  fraud_detection_analytics:
    raw_customers:
      +column_types:
        phone: varchar(20)
