fraud_detection:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'gold_db') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA', 'public') }}"
